#!/bin/bash

declare color='\e[93m'
declare wipe="\033[1m\033[0m"

declare INSTALL_BOOT="source $HOME/.bash.d/boot"

if grep -q "$INSTALL_BOOT" $HOME/.bashrc; then
    printf "Boot settings found in ${color}${HOME}.bashrc${wipe}. Skipping ...\n"
else
    echo $INSTALL_BOOT >> $HOME/.bashrc
    printf "Boot settings have been saved to your ${color}.bashrc${wipe} file.\n"
fi

for source_file in $HOME/.bash.d/dot-files/*; do
    target_file=$HOME/.$(basename $source_file)
    if [ ! -f $target_file ]; then
        printf "Linking ${color}${source_file}${wipe} to ${color}${target_file}${wipe}\n"
        ln -s $source_file $target_file
    else
        printf "${color}${target_file}${wipe} already exists. Skipping ...\n"
    fi
done

unset source_file
unset target_file
